### ISSUE TITLE
Update the BDK playground

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/bitcoindevkit.org#111]
It's using a really old version of `bdk-cli`, and returning wrong descriptors (with the miniscript bug) when you use thresh. We should update it so that it uses the last `bdk` (we can't use `bdk-cli` anymore as it's not a library)

Also, maybe it would be cool to have the REPL in a completely separated page? So we can have a playground for experimenting with policies and descriptors, and a whole different page for trying out BDK.

**Comment by michaelfolkson** [comment]
I was using the BDK [Playground](https://bitcoindevkit.org/bdk-cli/playground/) to quickly see whether the Rust Policy/Miniscript compiler output matched the C++ Policy/Miniscript compiler output and was going to open an issue for this but Daniela beat me to it :)

**Comment by danielabrozzoni** [comment]
If you want to test it out, https://github.com/bitcoindevkit/bitcoindevkit.org/pull/118 should solve the issue :)
