### ISSUE TITLE
Add example projects

### ISSUE THREAD

**Issue by ConorOkus** [bitcoindevkit/bitcoindevkit.org#119]
Similar to - https://lightningdevkit.org/examples/

**Comment by ConorOkus** [comment]
Karavan - https://github.com/notmandatory/karavan
Devkit-wallet - https://github.com/notmandatory/karavan
Padawan-wallet - https://github.com/thunderbiscuit/padawan-wallet

**Comment by thunderbiscuit** [comment]
The new case studies page fulfills that role now! We're also removing the examples/ endpoint, because it was cross-referencing things in the case studies page without a clear separate purpose.
