### ISSUE TITLE
Authors missing in tutorials

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bitcoindevkit.org#122]
The tutorial page doesn't show the tutorial authors like the blog posts. As many people (outside of BDK team) contributes to the tutorial site it would be nice to have them displayed as the author, just like the blog posts.. The Author metadata is already present in the tutorial md files, its just not displayed in the final webpage.

**Comment by thunderbiscuit** [comment]
We are moving the tutorials into blog posts. Closing this as it will no longer be an issue.
