### ISSUE TITLE
Create case studies page

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bitcoindevkit.org#143]
Should be similar to the one LDK created.  Since we don't have any in-depth case studies yet we can start with the projects building on BDK. Part of this effort will be to identify the projects using BDK, contact each once and get their OK to be added to the page plus develop a summary for each one and figure out what categories to put them in. 

For the web page design we should be able to more or less clone the template LDK used since we're both using the same web framework. 

https://lightningdevkit.org/case-studies/

cc: @ConorOkus

**Comment by thunderbiscuit** [comment]
We have added all known current projects using BDK in production (19 in total!) Closing this issue now.
