### ISSUE TITLE
Automatically re-generate docs-rs

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bitcoindevkit.org#5]
Currently the rust docs for `bdk` are manually re-generated and copied to the `bitcoindevkit.org` project, see [README.md](https://github.com/bitcoindevkit/bitcoindevkit.org/blob/master/README.md). It would be nice to automate this process to regenerate the latest `bdk` docs-rs pages and re-publish the `bitcoindevkit.org` website via the `gh-pages` branch when ever a new PR is committed to the `bdk/master` branch. This should be done without relying on a random docker image that would need to be trusted with a github access token.

**Comment by afilini** [comment]
Fixed by #15 and bitcoindevkit/bdk#209
