### ISSUE TITLE
Discord wants my phone number this time

### ISSUE THREAD

**Issue by rxgrant** [bitcoindevkit/bitcoindevkit.org#61]
I noticed I couldn't sign up for BDK's Discord without giving it a phone number.  I don't have a phone-number-worthy relationship with Discord.  

I hope you summarize your development plans early and often in blog posts.

**Comment by notmandatory** [comment]
Hi, sorry about the hassle with Discord requiring a phone number. I don't know anyway around this but we will be keeping our roadmap, issues, and PR discussions on GitHub so you can always participate that way. 

I understand for privacy issues some folks would like to avoid giving up their phone number to join our chat system. What chat systems that don't require a phone number do you prefer? Matrix, IRC, or something else? most of the active contributors on `bdk` are also on IRC, I'm on Libera.Chat as `notmandatory`.

**Comment by rxgrant** [comment]
Cool see you on Libera.
