### ISSUE TITLE
Add custom github `bitcoindevkit` organization README

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bitcoindevkit.org#62]
Add a custom `bitcoindevkit` organization README similar to the one done for the `lightningdevkit` org:

https://github.com/lightningdevkit

Suggested by @ConorOkus , he may have additional suggestions.

**Comment by artfuldev** [comment]
I'm gonna do a v0 of this and we can improve upon it.

**Comment by artfuldev** [comment]
Added the first version. We can keep updating it as and when required. @notmandatory

**Comment by notmandatory** [comment]
Looks good! I also added permissions so future changed will need a PR. 

https://github.com/bitcoindevkit
