### ISSUE TITLE
Update BDK-CLI section to match `bdk-cli` version 3.0

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bitcoindevkit.org#64]
Things to-do:
- [x] Installation section in wrong for esplora, see https://github.com/bitcoindevkit/bdk-cli/issues/53

**Comment by BitcoinABee** [comment]
Hello @notmandatory , 
I have the PR ready for the fix: https://github.com/bitcoindevkit/bitcoindevkit.org/pull/75

Thank you for the time!

**Comment by notmandatory** [comment]
This issue seemed to be causing the most confusion for new folks so thanks for getting it updated!
