### ISSUE TITLE
Footnotes not working anymore

### ISSUE THREAD

**Issue by RCasatta** [bitcoindevkit/bitcoindevkit.org#65]
I just noticed, markdown footnotes are not working anymore, see for example [^fee rate] in https://bitcoindevkit.org/blog/2021/01/fee-estimation-for-light-clients-part-1/

**Comment by notmandatory** [comment]
Good catch, didn't notice that. The Issue seems to be vuepress doesn't like spaces in the footnote tag, I'll fix it up today.
