### ISSUE TITLE
Starting electrs is throwing an error 

### ISSUE THREAD

**Issue by BitcoinABee** [bitcoindevkit/bitcoindevkit.org#78]
`electrs -vv --timestamp --db-dir /tmp/electrs-db --electrum-rpc-addr="127.0.0.1:50001" --network=regtest --cookie-file=$HOME/.bitcoin/regtest/.cookie
`
**Error: please use `log_filters` to set logging verbosity**

_Looks like -vv is deprecated in electrs_

**Comment by BitcoinABee** [comment]
Hi @notmandatory ,

I have created a PR with fix for this: https://github.com/bitcoindevkit/bitcoindevkit.org/pull/79 

Thank you so much for your time!

**Comment by notmandatory** [comment]
Thanks! it's merged so closing this issue. 
https://bitcoindevkit.org/bdk-cli/regtest/

**Comment by BitcoinABee** [comment]
Closing this out because the error got fixed with pr#79 

https://github.com/bitcoindevkit/bitcoindevkit.org/pull/79
