### ISSUE TITLE
Document structure improvement

### ISSUE THREAD

**Issue by rajarshimaitra** [bitcoindevkit/bitcoindevkit.org#83]
After porting the blogs and docs into new website, it seems there are rooms now to organize the documents better. 

 - The bdk-cli section https://bitcoindevkit.org/bdk-cli/installation/ could use an introduction.

 - Many blog posts are essentially tutorials, and they can be moved to the tutorial section.

 - Adding more smaller tutorials (how-tos) for common tasks like running regtest nodes etc and linking them to other tutorials.
 
 - More detailing in the getting started page.
 
 Other improvement ideas are welcome.
 
 Opening this up as a tracking issue.

**Comment by ConorOkus** [comment]
Would also be great to add runnable self-contained examples to the `bdk` main repo similar to this - https://github.com/vercel/next.js/tree/canary/examples and link to those from the website 👍

**Comment by rajarshimaitra** [comment]
@ConorOkus I opened https://github.com/bitcoindevkit/bdk/pull/519 adding one example in bdk. Let me know if you meant this kind of examples.

**Comment by ConorOkus** [comment]
Yeah awesome, didn't realise there were some examples already in there so that's great

**Comment by thunderbiscuit** [comment]
This issue is a bit stale, and all tutorials are being moved to the blog. We're also working on a standalone documentation site that will take the place of some of these tutorials (the book of bdk). Closing this issue now as part of a clean up of this repository.
