### ISSUE TITLE
Add `bdk` `bdk-cli` appendix to "Mastering Bitcoin" 2nd Edition

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bitcoindevkit.org#87]
@aantonop reached out in 2021 and asked if anyone on the BDK team would be interested in adding an appendix similar to the ones for [pycoin]. The [bitcoinbook] github is open for PRs.  Use existing website docs and blogs for ideas.

[bitcoinbook]: https://github.com/bitcoinbook/bitcoinbook
[pycoin]: https://github.com/bitcoinbook/bitcoinbook/blob/develop/appdx-pycoin.asciidoc

**Comment by notmandatory** [comment]
@waterst0ne is going to work on this one.

**Comment by notmandatory** [comment]
Fixed by bitcoinbook/bitcoinbook#1032

**Comment by somdipto** [comment]
is it still open then i would like to give it a try

**Comment by aantonop** [comment]
In the third edition, we decided to remove any library or tooling
appendices. Unfortunately this means we did not include bdk.
